<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>animations</key>
	<dict>
        <key>walk0</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_00.png</string>
                <string>mpl_01.png</string>
                <string>mpl_02.png</string>
                <string>mpl_03.png</string>
                <string>mpl_00.png</string>
            </array>
        </dict>
        <key>walk1</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_10.png</string>
                <string>mpl_11.png</string>
                <string>mpl_12.png</string>
                <string>mpl_13.png</string>
                <string>mpl_10.png</string>
            </array>
        </dict>
        <key>walk2</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_20.png</string>
                <string>mpl_21.png</string>
                <string>mpl_22.png</string>
                <string>mpl_23.png</string>
                <string>mpl_20.png</string>
            </array>
        </dict>
        <key>walk3</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_30.png</string>
                <string>mpl_31.png</string>
                <string>mpl_32.png</string>
                <string>mpl_33.png</string>
                <string>mpl_30.png</string>
            </array>
        </dict>
        <key>walk4</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_40.png</string>
                <string>mpl_41.png</string>
                <string>mpl_42.png</string>
                <string>mpl_43.png</string>
                <string>mpl_40.png</string>
            </array>
        </dict>
        <key>walk5</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_50.png</string>
                <string>mpl_51.png</string>
                <string>mpl_52.png</string>
                <string>mpl_53.png</string>
                <string>mpl_50.png</string>
            </array>
        </dict>
        <key>walk6</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_60.png</string>
                <string>mpl_61.png</string>
                <string>mpl_62.png</string>
                <string>mpl_63.png</string>
                <string>mpl_60.png</string>
            </array>
        </dict>
        <key>walk7</key>
        <dict>
            <key>delay</key>
            <real>0.05</real>
            <key>frames</key>
            <array>
                <string>mpl_70.png</string>
                <string>mpl_71.png</string>
                <string>mpl_72.png</string>
                <string>mpl_73.png</string>
                <string>mpl_70.png</string>
            </array>
        </dict>
	</dict>
</dict>
</plist>
